// Code generated by MockGen. DO NOT EDIT.
// Source: ./consumer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	units "github.com/go-sensors/core/units"
	gomock "github.com/golang/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleRelativeHumidity mocks base method.
func (m *MockHandler) HandleRelativeHumidity(arg0 *units.RelativeHumidity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRelativeHumidity", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleRelativeHumidity indicates an expected call of HandleRelativeHumidity.
func (mr *MockHandlerMockRecorder) HandleRelativeHumidity(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRelativeHumidity", reflect.TypeOf((*MockHandler)(nil).HandleRelativeHumidity), arg0)
}
