// Code generated by MockGen. DO NOT EDIT.
// Source: ./consumer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gas "github.com/go-sensors/core/gas"
	gomock "github.com/golang/mock/gomock"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// HandleGasConcentration mocks base method.
func (m *MockHandler) HandleGasConcentration(arg0 context.Context, arg1 *gas.Concentration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleGasConcentration", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleGasConcentration indicates an expected call of HandleGasConcentration.
func (mr *MockHandlerMockRecorder) HandleGasConcentration(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleGasConcentration", reflect.TypeOf((*MockHandler)(nil).HandleGasConcentration), arg0, arg1)
}
