// Code generated by MockGen. DO NOT EDIT.
// Source: ./definition.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pm "github.com/go-sensors/core/pm"
	gomock "github.com/golang/mock/gomock"
)

// MockParticulateMatterSensor is a mock of ParticulateMatterSensor interface.
type MockParticulateMatterSensor struct {
	ctrl     *gomock.Controller
	recorder *MockParticulateMatterSensorMockRecorder
}

// MockParticulateMatterSensorMockRecorder is the mock recorder for MockParticulateMatterSensor.
type MockParticulateMatterSensorMockRecorder struct {
	mock *MockParticulateMatterSensor
}

// NewMockParticulateMatterSensor creates a new mock instance.
func NewMockParticulateMatterSensor(ctrl *gomock.Controller) *MockParticulateMatterSensor {
	mock := &MockParticulateMatterSensor{ctrl: ctrl}
	mock.recorder = &MockParticulateMatterSensorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParticulateMatterSensor) EXPECT() *MockParticulateMatterSensorMockRecorder {
	return m.recorder
}

// ConcentrationSpecs mocks base method.
func (m *MockParticulateMatterSensor) ConcentrationSpecs() []*pm.ConcentrationSpec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConcentrationSpecs")
	ret0, _ := ret[0].([]*pm.ConcentrationSpec)
	return ret0
}

// ConcentrationSpecs indicates an expected call of ConcentrationSpecs.
func (mr *MockParticulateMatterSensorMockRecorder) ConcentrationSpecs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConcentrationSpecs", reflect.TypeOf((*MockParticulateMatterSensor)(nil).ConcentrationSpecs))
}

// Concentrations mocks base method.
func (m *MockParticulateMatterSensor) Concentrations() <-chan *pm.Concentration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Concentrations")
	ret0, _ := ret[0].(<-chan *pm.Concentration)
	return ret0
}

// Concentrations indicates an expected call of Concentrations.
func (mr *MockParticulateMatterSensorMockRecorder) Concentrations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Concentrations", reflect.TypeOf((*MockParticulateMatterSensor)(nil).Concentrations))
}

// Run mocks base method.
func (m *MockParticulateMatterSensor) Run(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockParticulateMatterSensorMockRecorder) Run(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockParticulateMatterSensor)(nil).Run), arg0)
}
